name: Auto Deploy

on:
  schedule:
    - cron: "0 0 * * *"
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      deploy: ${{ steps.set-output.outputs.deploy }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check if deployment is needed
        id: set-output
        shell: bash
        run: ./scripts/check-deploy.sh

  build:
    needs: check
    if: needs.check.outputs.deploy == 'true'
    name: Build
    uses: ./.github/workflows/build.yml

  deploy:
    needs: build
    name: Publish to the `gh-pages` branch
    permissions:
      contents: write
    uses: ./.github/workflows/publish.yml
    with:
      destination_dir: ./
